# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KSAwHaJ4-L0a5_AfEgCDYyYfF4Pv4IY
"""

! pip install -U scikit-fuzzy
! pip install -e
! pip install -e ".[develop]"

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# đầu vào
rating=ctrl.Antecedent(np.arange(0,5.1,0.1),'rating')
volume = ctrl.Antecedent(np.arange(0, 101, 1), 'volume')
margin = ctrl.Antecedent(np.arange(0, 101, 1), 'margin')
event = ctrl.Antecedent(np.arange(0, 11, 1), 'event')
competitor = ctrl.Antecedent(np.arange(0, 101, 1), 'competitor')

#đầu ra
discount=ctrl.Consequent(np.arange(0,71,1),'discount')
# xây dựng biểu đồ
rating['low'] = fuzz.trimf(rating.universe, [0, 0, 4.0])
rating['medium'] = fuzz.trimf(rating.universe, [4.0, 4.25, 4.5])
rating['high'] = fuzz.trimf(rating.universe, [4.5, 5.0, 5.0])

volume['low'] = fuzz.trimf(volume.universe,[0,0,25] )
volume['medium'] = fuzz.trimf(volume.universe,[25,50,75] )
volume['high'] = fuzz.trimf(volume.universe,[50,100,100] )


margin['low'] = fuzz.trimf(margin.universe,[0,0,25] )
margin['medium'] = fuzz.trimf(margin.universe,[25,50,75] )
margin['high'] = fuzz.trimf(margin.universe,[75,100,100] )


event['none'] = fuzz.trimf(event.universe, [0,0,2.5])
event['moderate'] = fuzz.trimf(event.universe, [2.5,5,7.5])
event['high'] = fuzz.trimf(event.universe, [7.5,10,10 ])


competitor['low'] = fuzz.trimf(competitor.universe,[0,0,25] )
competitor['medium'] = fuzz.trimf(competitor.universe,[25,50,75] )
competitor['high'] = fuzz.trimf(competitor.universe, [75,100,100])


discount['very_low'] = fuzz.trimf(discount.universe, [0, 2.5, 5])
discount['low'] = fuzz.trimf(discount.universe, [5, 7.5, 10])
discount['medium'] = fuzz.trimf(discount.universe, [10, 15, 20])
discount['high'] = fuzz.trimf(discount.universe, [20, 30, 40])
discount['very_high'] = fuzz.trimf(discount.universe, [40, 55, 70])


#Luật mờ
rule1 = ctrl.Rule(rating['high'] & volume['high'] & margin['high'], discount['very_low'])
rule2 = ctrl.Rule(rating['low'] & volume['low'] & margin['high'], discount['high'])
rule3 = ctrl.Rule(event['high'] & competitor['high'], discount['very_high'])
rule4 = ctrl.Rule(rating['medium'] & volume['medium'] & margin['medium'], discount['medium'])
rule5 = ctrl.Rule(competitor['low'] & margin['low'] & volume['high'], discount['very_low'])
rule6 = ctrl.Rule(rating['low'] & event['none'], discount['medium'])
rule7 = ctrl.Rule(volume['low'] & margin['low'], discount['very_high'])


discount_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7])
discount_sim = ctrl.ControlSystemSimulation(discount_ctrl)

discount_sim.input['rating'] = 4.3
discount_sim.input['volume'] = 60
discount_sim.input['margin'] = 20
discount_sim.input['event'] = 8
discount_sim.input['competitor'] = 80


discount_sim.compute()


#hiển thị kết quả
print(f"Mức CHIẾT KHẤU đề xuất cho Shopee: {discount_sim.output['discount']:.2f}%")
discount.view(sim=discount_sim)