# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DcLvKZA5lJhDsuBinX909D_b-BhhWaQ
"""

!pip install -U scikit-fuzzy
!pip install -e
!pip install -e ".[develop]"

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import itertools

# Đầu vào
distance = ctrl.Antecedent(np.arange(0, 51, 1), 'distance')
traffic = ctrl.Antecedent(np.arange(0, 101, 1), 'traffic')
demand = ctrl.Antecedent(np.arange(0, 101, 1), 'demand')
weather = ctrl.Antecedent(np.arange(0, 11, 1), 'weather')
rating = ctrl.Antecedent(np.arange(1.0, 5.1, 0.1), 'rating')
punctuality = ctrl.Antecedent(np.arange(0, 101, 1), 'punctuality')

# Đầu ra
price = ctrl.Consequent(np.arange(0, 101, 1), 'price')
bonus = ctrl.Consequent(np.arange(0, 101, 1), 'bonus')

#Quãng đường
distance['short'] = fuzz.trimf(distance.universe, [0, 0, 15])
distance['medium'] = fuzz.trimf(distance.universe, [5, 15, 25])
distance['long'] = fuzz.trimf(distance.universe, [15, 30, 45])
distance['very_long'] = fuzz.trimf(distance.universe, [35, 50, 50])

# Giao thông
traffic['low'] = fuzz.trimf(traffic.universe, [0, 0, 30])
traffic['medium'] = fuzz.trimf(traffic.universe, [20, 50, 80])
traffic['high'] = fuzz.trimf(traffic.universe, [70, 100, 100])

# Mức cầu
demand['low'] = fuzz.trimf(demand.universe, [0, 0, 40])
demand['medium'] = fuzz.trimf(demand.universe, [20, 50, 80])
demand['high'] = fuzz.trimf(demand.universe, [60, 100, 100])

# Thời tiết
weather['good'] = fuzz.trimf(weather.universe, [7, 10, 10])
weather['moderate'] = fuzz.trimf(weather.universe, [2, 4, 9])
weather['bad'] = fuzz.trimf(weather.universe, [0, 0, 3])

# Đánh giá
rating['poor'] = fuzz.trimf(rating.universe, [1.0, 1.0, 2.5])
rating['average'] = fuzz.trimf(rating.universe, [2.0, 3.0, 4.0])
rating['good'] = fuzz.trimf(rating.universe, [3.5, 5.0, 5.0])

# Đúng giờ
punctuality['late'] = fuzz.trimf(punctuality.universe, [0, 0, 30])
punctuality['on_time'] = fuzz.trimf(punctuality.universe, [20, 50, 80])
punctuality['early'] = fuzz.trimf(punctuality.universe, [70, 100, 100])

# Đầu ra
# Giá cước
price['low'] = fuzz.trimf(price.universe, [0, 0, 30])
price['medium'] = fuzz.trimf(price.universe, [20, 50, 80])
price['high'] = fuzz.trimf(price.universe, [60, 85, 100])
price['very_high'] = fuzz.trimf(price.universe, [75, 100, 100])

# Điểm thưởng
bonus['none'] = fuzz.trimf(bonus.universe, [0, 0, 20])
bonus['few'] = fuzz.trimf(bonus.universe, [10, 30, 50])
bonus['moderate'] = fuzz.trimf(bonus.universe, [40, 60, 80])
bonus['high'] = fuzz.trimf(bonus.universe, [70, 100, 100])

rule1 = ctrl.Rule(distance['short'] & traffic['low'] & demand['low'], price['low'])
rule2 = ctrl.Rule(distance['short'] & traffic['medium'] & demand['high'], price['medium'])
rule3 = ctrl.Rule(distance['medium'] & traffic['high'] & demand['high'], price['high'])
rule4 = ctrl.Rule(distance['long'] & traffic['medium'] & weather['good'], price['medium'])
rule5 = ctrl.Rule(distance['long'] & traffic['high'] & weather['bad'], price['very_high'])
rule6 = ctrl.Rule(distance['short'] & traffic['high'] & demand['high'], price['very_high'])
rule7 = ctrl.Rule(distance['medium'] & traffic['low'] & demand['low'], price['medium'])
rule8 = ctrl.Rule(distance['short'] & traffic['high'] & weather['bad'], price['high'])
rule9 = ctrl.Rule(distance['very_long'] & weather['bad'], price['very_high'])
rule10 = ctrl.Rule(distance['medium'] & traffic['medium'] & weather['good'], price['medium'])
rule11 = ctrl.Rule(distance['long'] & traffic['low'] & demand['high'], price['high'])
rule12 = ctrl.Rule(distance['short'] & traffic['medium'] & demand['low'], price['low'])
rule13 = ctrl.Rule(distance['medium'] & traffic['high'] & demand['low'], price['medium'])
rule14 = ctrl.Rule(distance['short'] & traffic['high'] & weather['good'], price['high'])
rule15 = ctrl.Rule(distance['long'] & traffic['medium'] & demand['high'], price['medium'])
rule16 = ctrl.Rule(distance['medium'] & traffic['low'] & demand['high'], price['high'])
rule17 = ctrl.Rule(distance['short'] & traffic['low'] & demand['high'], price['very_high'])
rule18 = ctrl.Rule(distance['long'] & traffic['high'] & demand['low'], price['high'])
rule19 = ctrl.Rule(distance['short'] & traffic['high'] & weather['good'], price['high'])
rule20 = ctrl.Rule(distance['medium'] & traffic['medium'] & demand['low'], price['medium'])
rule21 = ctrl.Rule(rating['good']& punctuality['early'], bonus['high'])
rule22 = ctrl.Rule(rating['average']& punctuality['on_time'], bonus['moderate'])
rule23 = ctrl.Rule(rating['poor']& punctuality['late'], bonus['none'])
rule24 = ctrl.Rule(distance['long']& traffic['high'] & punctuality['on_time'], bonus['high'])
rule25 = ctrl.Rule(distance['short']& traffic['low'] & punctuality['late'], bonus['none'])
rule26 = ctrl.Rule(distance['medium']& weather['moderate'] & rating['good'], bonus['moderate'])
rule27 = ctrl.Rule(distance['short']& traffic['high'] & punctuality['late'], bonus['none'])
rule28 = ctrl.Rule(distance['very_long']& weather['bad'] & rating['good'], bonus['high'])
rule29 = ctrl.Rule(distance['long']& weather['good'] & rating['average'], bonus['moderate'])
rule30 = ctrl.Rule(distance['short']& weather['bad'] & rating['poor'], bonus['none'])
rule31 = ctrl.Rule(punctuality['late'] & rating['poor'], bonus['none'])
rule32 = ctrl.Rule(punctuality['on_time'] & rating['average'], bonus['moderate'])
rule33 = ctrl.Rule(punctuality['early'] & rating['good'], bonus['high'])

price_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10, rule11, rule12, rule13, rule14, rule15, rule16, rule17, rule18, rule19, rule20, rule21, rule22, rule23, rule24, rule25, rule26, rule27, rule28, rule29, rule30, rule31, rule32, rule33])
price_sim = ctrl.ControlSystemSimulation(price_ctrl)

price_sim.input['distance'] = 4.5
price_sim.input['traffic'] = 80
price_sim.input['demand'] = 85
price_sim.input['weather'] = 8
price_sim.input['rating'] = 4.5
price_sim.input['punctuality'] = 80

price_sim.compute()

print("Mức giá cước tính toán được (%):", price_sim.output['price'])
price.view(sim=price_sim)
print("Điểm thưởng tính toán được (%):", price_sim.output['bonus'])
bonus.view(sim=price_sim)