# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Du24GtR4D__S89MnRPxKnL6dQ4bVRTVP
"""

! pip install -U scikit-fuzzy
! pip install -e
! pip install -e ".[develop]"

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# =========================================================
# 1. THIẾT LẬP 5 BIẾN ĐẦU VÀO & 1 BIẾN ĐẦU RA [1]
# =========================================================
# Khởi tạo các biến đầu vào
demand = ctrl.Antecedent(np.arange(0, 101, 1), 'demand')             # Nhu cầu sản phẩm (0-100%)
pressure = ctrl.Antecedent(np.arange(0, 101, 1), 'pressure')         # Áp lực định giá từ đối thủ (0-100%)
reputation = ctrl.Antecedent(np.arange(0, 5.1, 0.1), 'reputation')   # Uy tín cửa hàng (0-5.0 sao)
margin = ctrl.Antecedent(np.arange(0, 101, 1), 'margin')             # Biên lợi nhuận (0-100%)
seasonal = ctrl.Antecedent(np.arange(0, 101, 1), 'seasonal')         # Nhu cầu theo mùa (0-100%)

# Khởi tạo biến đầu ra
discount = ctrl.Consequent(np.arange(0, 71, 1), 'discount')          # Mức giảm giá (0-70%)

# =========================================================
# 2. XÂY DỰNG BIỂU ĐỒ HÀM LIÊN THUỘC (THAY SỐ CỤ THỂ) [1, 2]
# =========================================================
# 1. Nhu cầu sản phẩm: Thấp, Trung bình, Cao
demand['low'] = fuzz.trimf(demand.universe,[0,0,25] )
demand['medium'] = fuzz.trimf(demand.universe,[25,50,75] )
demand['high'] = fuzz.trimf(demand.universe,[75,100,100] )

# 2. Áp lực định giá của đối thủ: Thấp, Trung bình, Cao
pressure['low'] = fuzz.trimf(pressure.universe,[0,0,25] )
pressure['medium'] = fuzz.trimf(pressure.universe,[25,50,75] )
pressure['high'] = fuzz.trimf(pressure.universe,[75,100,100] )

# 3. Uy tín cửa hàng: Thấp (<4.0), Trung bình (4.0-4.5), Cao (>4.5)
reputation['low'] = fuzz.trimf(reputation.universe, [0, 0, 4.0])
reputation['medium'] = fuzz.trimf(reputation.universe, [4.0, 4.25, 4.5])
reputation['high'] = fuzz.trimf(reputation.universe, [4.5, 5.0, 5.0])

# 4. Biên lợi nhuận: Thấp, Trung bình, Cao
margin['low'] = fuzz.trimf(margin.universe,[0,0,25] )
margin['medium'] = fuzz.trimf(margin.universe, [25,50,75])
margin['high'] = fuzz.trimf(margin.universe, [75,100,100])

# 5. Nhu cầu theo mùa: Không có, Trung bình, Cao
seasonal['none'] = fuzz.trimf(seasonal.universe,[0,0,25] )
seasonal['medium'] = fuzz.trimf(seasonal.universe,[25,50,75] )
seasonal['high'] = fuzz.trimf(seasonal.universe, [75,100,100])

# 6. Biến đầu ra (Mức giảm giá) theo các mốc phần trăm cụ thể trong sách
discount['very_low'] = fuzz.trimf(discount.universe, [0, 2.5, 5])     # Rất thấp (0-5%)
discount['low'] = fuzz.trimf(discount.universe, [5, 7.5, 10])         # Thấp (5-10%)
discount['medium'] = fuzz.trimf(discount.universe, [10,15,20])      # Trung bình (10-20%)
discount['high'] = fuzz.trimf(discount.universe,[20,30,40] )        # Cao (20-40%)
discount['very_high'] = fuzz.trimf(discount.universe,[40,55,70] )   # Rất cao (40-70%)

# =========================================================
# 3. KHỞI TẠO 7 LUẬT MỜ [2]
# =========================================================
rule1 = ctrl.Rule(demand['high'] & pressure['low'] & margin['low'], discount['very_low'])
rule2 = ctrl.Rule(demand['low'] & pressure['high'] & margin['high'], discount['high'])
rule3 = ctrl.Rule(reputation['high'] & margin['medium'] & seasonal['high'], discount['medium'])
rule4 = ctrl.Rule(pressure['high'] & seasonal['high'] & margin['high'], discount['very_high'])
rule5 = ctrl.Rule(reputation['low'] & demand['medium'] & margin['low'], discount['medium'])
rule6 = ctrl.Rule(demand['medium'] & seasonal['none'] & pressure['low'], discount['very_low'])
rule7 = ctrl.Rule(margin['high'] & pressure['medium'] & seasonal['medium'], discount['medium'])

# =========================================================
# 4. TẠO HỆ THỐNG VÀ KIỂM THỬ TÌNH HUỐNG TRONG SÁCH [2]
# =========================================================
discount_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7])
discount_sim = ctrl.ControlSystemSimulation(discount_ctrl)

# Nhập dữ liệu của cửa hàng Đồng hồ xa xỉ thủ công theo đề bài
discount_sim.input['demand'] = 80       # Nhu cầu sản phẩm: Cao (90%)
discount_sim.input['pressure'] = 80     # Áp lực cạnh tranh: Thay đổi từ 50% lên 80% để kích hoạt Rule 4
discount_sim.input['reputation'] = 4.4  # Uy tín: Trung bình (4.2 sao)
discount_sim.input['margin'] = 90       # Biên lợi nhuận: Cao (90%)
discount_sim.input['seasonal'] = 77     # Nhu cầu theo mùa: Cao (Khuyến mãi 11.11 -> 90%)

# Thực thi tính toán [7]
discount_sim.compute()

# In kết quả và vẽ đồ thị
print(f"Mức GIẢM GIÁ đề xuất cho mặt hàng đặc biệt: {discount_sim.output['discount']:.2f}%")
discount.view(sim=discount_sim)